"""Generates the default docxtpl templates in docgen/templates/ from scratch via
python-docx. Run once (or whenever the default layout changes) to regenerate the
binary .docx files that get committed to the repo. The landlord's own styled copies
on the Pi (data/templates/) are edited directly in Word and never regenerated by
this script — see docs/legal-requirements.md §6 / the deployment plan.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.shared import Pt

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "docgen" / "templates"


def _add_header_block(doc: Document, title: str) -> None:
    p = doc.add_paragraph()
    p.add_run("{{ landlord.name }}\n{{ landlord.address }}").font.size = Pt(10)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("{{ tenant_name }}\n{{ tenant_address }}").font.size = Pt(11)

    doc.add_paragraph()
    doc.add_heading(title, level=1)

    p = doc.add_paragraph()
    p.add_run(
        "Objekt: {{ property_label }}, {{ property_address }}\n"
        "Wohnung: {{ unit_label }}\n"
        "Abrechnungszeitraum: {{ billing_period_start }} bis {{ billing_period_end }}"
    )


def _add_repeating_row_table(
    doc: Document, headers: list[str], loop_var: str, loop_iter: str
) -> Document.tables:
    table = doc.add_table(rows=0, cols=len(headers))
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    header_row = table.add_row()
    for cell, text in zip(header_row.cells, headers):
        cell.text = text
        for run in cell.paragraphs[0].runs:
            run.bold = True

    control_start = table.add_row()
    control_start.cells[0].text = f"{{%tr for {loop_var} in {loop_iter} %}}"

    return table


def generate_betriebskostenabrechnung(garage: bool = False) -> None:
    doc = Document()
    title = "Betriebskostenabrechnung" + (" (Garage)" if garage else "")
    _add_header_block(doc, title)

    headers = [
        "Kostenart",
        "Gesamtkosten Gebäude",
        "Verteilerschlüssel",
        "Ihr Anteil (Berechnung)",
        "Betrag",
    ]
    table = _add_repeating_row_table(doc, headers, "line", "cost_lines")

    template_row = table.add_row()
    template_row.cells[0].text = "{{ line.cost_type_name }}"
    template_row.cells[1].text = "{{ line.total_building_cost }}"
    template_row.cells[2].text = "{{ line.distribution_key_description }}"
    template_row.cells[3].text = "{{ line.tenant_share_calculation }}"
    template_row.cells[4].text = "{{ line.tenant_share_amount }}"

    control_end = table.add_row()
    control_end.cells[0].text = "{%tr endfor %}"

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("Gesamtbetriebskosten: {{ total_tenant_cost }}\n").bold = True
    p.add_run("Abzüglich Vorauszahlungen: {{ advance_payments_total }}\n")
    p.add_run("{{ balance_label }}: {{ balance }}").bold = True

    doc.add_paragraph()
    doc.add_paragraph(
        "Diese Abrechnung muss Ihnen gemäß § 556 Abs. 3 BGB spätestens bis zum "
        "{{ deadline_date }} zugegangen sein. Die zugrunde liegenden Belege können "
        "bei Bedarf eingesehen werden."
    )

    filename = "betriebskostenabrechnung_garage.docx" if garage else "betriebskostenabrechnung.docx"
    doc.save(TEMPLATES_DIR / filename)


def generate_wasserkostenabrechnung() -> None:
    doc = Document()
    _add_header_block(doc, "Wasserkostenabrechnung")

    headers = ["Zähler-Nr.", "Art", "Ablesewert alt", "Ablesewert neu", "Verbrauch"]
    table = _add_repeating_row_table(doc, headers, "m", "meter_lines")

    template_row = table.add_row()
    template_row.cells[0].text = "{{ m.meter_id }}"
    template_row.cells[1].text = "{{ m.meter_type }}"
    template_row.cells[2].text = "{{ m.reading_old }}"
    template_row.cells[3].text = "{{ m.reading_new }}"
    template_row.cells[4].text = "{{ m.consumption }}"

    control_end = table.add_row()
    control_end.cells[0].text = "{%tr endfor %}"

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run(
        "Gesamtverbrauch aller Mietparteien: {{ building_consumption_total }} m³\n"
        "Ihr Verbrauch: {{ tenant_consumption_total }} m³\n\n"
    )
    p.add_run("Berechnung: {{ tenant_share_calculation }}\n").bold = True

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("Ihr Anteil an den Wasserkosten: {{ tenant_share_amount }}\n").bold = True
    p.add_run("Abzüglich Vorauszahlungen: {{ advance_payments_total }}\n")
    p.add_run("{{ balance_label }}: {{ balance }}").bold = True

    doc.save(TEMPLATES_DIR / "wasserkostenabrechnung.docx")


def generate_heizkostenabrechnung() -> None:
    doc = Document()
    _add_header_block(doc, "Heizkostenabrechnung")

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run(
        "Gesamtkosten der Liegenschaft: {{ gesamtkosten_liegenschaft }}\n"
        "Anteil des Vermieters an den CO2-Kosten: {{ co2_landlord_share }}\n"
    )

    doc.add_heading("Heizung", level=2)
    p = doc.add_paragraph()
    p.add_run(
        "Grundkosten (Gebäude): {{ heating.grundkosten_total }}\n"
        "{{ heating.grundkosten_calculation }}\n\n"
        "Verbrauchskosten (Gebäude): {{ heating.verbrauch_total }}\n"
        "{{ heating.verbrauch_calculation }}\n\n"
    )
    p.add_run(
        "Ihr Anteil Heizung: {{ heating.tenant_grundkosten }} + {{ heating.tenant_verbrauch }}"
    ).bold = True

    p = doc.add_paragraph()
    p.add_run("{% if warmwater %}")
    doc.add_heading("Warmwasser", level=2)
    p = doc.add_paragraph()
    p.add_run(
        "Grundkosten (Gebäude): {{ warmwater.grundkosten_total }}\n"
        "{{ warmwater.grundkosten_calculation }}\n\n"
        "Verbrauchskosten (Gebäude): {{ warmwater.verbrauch_total }}\n"
        "{{ warmwater.verbrauch_calculation }}\n\n"
    )
    p.add_run(
        "Ihr Anteil Warmwasser: {{ warmwater.tenant_grundkosten }} + {{ warmwater.tenant_verbrauch }}"
    ).bold = True
    doc.add_paragraph("{% endif %}")

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("{% if not metering_compliant %}")
    p.add_run(
        "Hinweis: Die Verbrauchserfassung entspricht nicht den Anforderungen der "
        "Heizkostenverordnung; gemäß § 12 HeizkostenV wurde eine Kürzung um 15% "
        "vorgenommen (bereits berücksichtigt).\n"
    )
    p.add_run("{% endif %}")

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("Ihre Heiz- und Warmwasserkosten: {{ tenant_total }}\n").bold = True
    p.add_run("Abzüglich Vorauszahlungen: {{ advance_payments_total }}\n")
    p.add_run("{{ balance_label }}: {{ balance }}").bold = True

    doc.save(TEMPLATES_DIR / "heizkostenabrechnung.docx")


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    generate_betriebskostenabrechnung(garage=False)
    generate_betriebskostenabrechnung(garage=True)
    generate_wasserkostenabrechnung()
    generate_heizkostenabrechnung()
    print(f"Generated 4 default templates in {TEMPLATES_DIR}")


if __name__ == "__main__":
    main()
